version: '3'

services:
  wordpress:
    container_name: wordpress
    image: wordpress:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - type: bind
        source: ./wp-app
        target: /var/www/html
        consistency: cached
      - ./wp-app/wp-content/plugins:/var/www/html/wp-content/plugins
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - database
      - meilisearch
    networks:
      - meili

  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v0.29
    restart: always
    ports:
      - "7700:7700"
    environment:
      - http_proxy
      - https_proxy
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_ENV=${MEILI_ENV}
    volumes:
      - ./meili_data:/data.ms
    networks:
      - meili

  wp_cli:
    container_name: wp_cli
    image: wordpress:cli
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - database
      - wordpress
    networks:
      - meili

  database:
    container_name: database
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    command: [
      '--authentication_policy=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    networks:
      - meili

networks:
  meili:
    driver: bridge

volumes:
  wp-app:
  db_data: